language: php

php:
 - 5.6
 - 7.0
 - 7.1

before_script:
  - cp .env .env.example
  - mysql -e 'create database todolist_tests;'
  - composer install --prefer-source --no-interaction

script:
  - vendor/bin/phpunit
